---
stages:
  -  build
  -  deploy

run_integration_tests:
  stage: build
  tags:
    - docker
  image: chef/chefdk:latest
  script:
    # Accept the version number to install from a URL trigger param
    - sed "s/XXX-XXX-XXX-XXX-XXX'/${AGENT_KEY}/" .kitchen.yml > .kitchen.local.yml
    - kitchen list
    # - kitchen test outlyer-agent-ubuntu-1604
