---
stages:
  -  build
  -  deploy

foodcritic:
  stage: build
  tags:
    - docker
  image: chef/chefdk
  script:
    - foodcritic ./

test_16.04:
  stage: build
  tags:
    - docker
  image: chef/chefdk
  script:
    - kitchen test outlyer-agent-ubuntu-1604
  after_script:
    - kitchen destroy
  when: manual

test_all:
  stage: build
  tags:
    - docker
  image: chef/chefdk
  script:
    - kitchen test
  after_script:
    - kitchen destroy
  when: manual
