---
driver:
  name: vagrant
  boot_timeout: 1200
  customize:
    cpus: 2
    memory: 2048
  gui: false

site_cookbooks_dir: site-cookbook

provisioner:
  data_path: data
  product_name: chef
  product_version: 13

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  #- name: centos-6.4
  - name: centos-7
  #- name: centos-7.2
  - name: centos-7.3
  - name: win7x86
  - name: windows-2012r2
    driver:
      name: ec2
    transport:
      username: administrator
      ssh_key: ~/.ssh/kitchen-test.pem
  #- name: winky/amazonlinux-2
  - name: amazonlinux-2
    driver:
      name: ec2
      image_id: ami-428aa838
    transport:
      username: ec2-user
      ssh_key: ~/.ssh/kitchen-test.pem

suites:
  - name: outlyer-agent
    run_list:
      - recipe[outlyer-agent]
    verifier:
      inspec_tests:
        - test
      # https://github.com/chef/kitchen-inspec#use-remote-inspec-profiles
      attrs:
        - test/integration_test.yml
    attributes:
        outlyer:
            agent:
              version: nil
              package_distribution: stable
              agent_key: XXX-XXX-XXX-XXX-XXX
              labels:
                role: test333
              #server: 'wss://alpha-agent.outlyer.com'
  #- name: compliance-test
  #  run_list:
  #    - recipe[outlyer-agent]
  #  verifier:
  #    inspec_tests:
  #      - https://github.com/dev-sec/linux-baseline.git

verifier:
  name: inspec
