Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-16.04"
  c.vm.hostname = "outlyer-agent-ubuntu-1604.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>443, :host=>8443})
  c.vm.network(:forwarded_port, {:guest=>9001, :host=>9001})
  c.vm.network(:forwarded_port, {:guest=>8091, :host=>8091})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/oliver/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--cpus", "2"]
    p.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
